export const EXAMPLE_PATH = 'nnejourneys.com'
export const CMS_NAME = 'North by Northeast Journeys'
export const baseURL='/'
export const imgblurDataURL='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mPsqQcAAZ0BDTSBuAQAAAAASUVORK5CYII='
export const HOME_OG_IMAGE_URL ='https://nxne.vercel.app/images/og-logo.png'
